# Generated by Django 3.2 on 2023-01-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeckFromExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setId', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('isBasedDeck', models.BooleanField()),
                ('isSpeedDuel', models.BooleanField()),
                ('setType', models.CharField(max_length=20)),
                ('setCode', models.CharField(max_length=20)),
            ],
        ),
    ]
