# Generated by Django 5.0.3 on 2024-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setId', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
