# Generated by Django 5.0.3 on 2025-01-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytypes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
