# Generated by Django 5.0.3 on 2025-02-08 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.SmallIntegerField()),
                ('attack', models.SmallIntegerField()),
                ('defense', models.SmallIntegerField()),
                ('sp_atk', models.SmallIntegerField()),
                ('sp_def', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_from', to='pokemon.pokemon')),
                ('evolves_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_to', to='pokemon.pokemon')),
                ('type', models.ManyToManyField(related_name='pokemons', to='pokemon_types.pokemontypes')),
            ],
        ),
    ]
