# Generated by Django 4.1.5 on 2023-01-12 02:23

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('api', 'Student')
    Student(name="Alan Naicson", email="naicson@hotmail.com", document="1461365406", phone="96959909").save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
