# Generated by Django 5.0.3 on 2025-02-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
        ('pokemon_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=455, null=True)),
                ('hit_point', models.SmallIntegerField()),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(max_length=100)),
                ('image_small', models.CharField(blank=True, max_length=200, null=True)),
                ('image_large', models.CharField(blank=True, max_length=200, null=True)),
                ('card_name', models.CharField(max_length=100)),
                ('hp', models.SmallIntegerField()),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('ex_rule', models.CharField(blank=True, max_length=455, null=True)),
                ('weakness', models.CharField(blank=True, max_length=50, null=True)),
                ('resistance', models.CharField(blank=True, max_length=50, null=True)),
                ('retreat', models.CharField(blank=True, max_length=50, null=True)),
                ('pokemon_description', models.CharField(blank=True, max_length=250, null=True)),
                ('ability_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ability_description', models.CharField(blank=True, max_length=450, null=True)),
                ('attack', models.ManyToManyField(blank=True, null=True, related_name='attack', to='card.attack')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemon.pokemon')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pokemon_types.pokemontypes')),
            ],
        ),
    ]
