# Generated by Django 5.0.3 on 2025-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='pokemon',
            new_name='pokemon_id',
        ),
    ]
