# Generated by Django 5.0.3 on 2025-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='own_this_card',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
