# Generated by Django 5.0.3 on 2025-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_own_this_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
