# Generated by Django 5.0.3 on 2025-02-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_types', '0002_pokemontypes_presentation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemontypes',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
